
from astra.pipelines.aspcap import corrections
corrections.flag_boundaries_and_abundances()
corrections.flag_upper_limits_by_hayes_2022()
corrections.apply_flags()
corrections.apply_dr19_irfm_corrections()
corrections.apply_dr19_logg_corrections()
corrections.apply_m_dwarf_logg_correction()
corrections.apply_dr19_solar_neighbourhood_abundance_corrections()
